INSERT INTO adopcion (
    mascota_id, 
    tamaño, 
    hogar, 
    edad, 
    compatible_con_ninos, 
    compatible_con_otros_animales, 
    nivel_actividad, 
    temperamento, 
    imagen, 
    animal, 
    descripcion, 
    requisitos_cuidados
)
VALUES
(1, 'pequeño', 'apartamento', 'cria', TRUE, TRUE, 'media', 'jugueton', 'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Gato', 'Un gato pequeño y activo ideal para apartamentos.', 'Requiere juguetes y un espacio limpio.'),
(2, 'mediano', 'apartamento', 'joven', TRUE, TRUE, 'alta', 'curioso', 'https://images.pexels.com/photos/248280/pexels-photo-248280.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Gato', 'Un gato joven que necesita espacio para explorar.', 'Requiere tiempo de juego diario.'),
(3, 'mediano', 'apartamento', 'adulto', TRUE, FALSE, 'baja', 'tranquilo', 'https://images.pexels.com/photos/208984/pexels-photo-208984.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Gato', 'Un gato adulto ideal para hogares tranquilos.', 'Requiere visitas regulares al veterinario.'),
(4, 'pequeño', 'casa', 'cria', TRUE, TRUE, 'alta', 'jugueton', 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg', 'Perro', 'Un cachorro pequeño ideal para familias activas.', 'Necesita entrenamiento básico y ejercicio.'),
(5, 'mediano', 'casa', 'joven', TRUE, TRUE, 'alta', 'protector', 'https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Perro', 'Un perro joven con energía y lealtad.', 'Requiere caminatas diarias y socialización.'),
(6, 'grande', 'casa', 'adulto', FALSE, FALSE, 'media', 'tranquilo', 'https://images.pexels.com/photos/1870301/pexels-photo-1870301.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Perro', 'Un perro adulto ideal para guardia.', 'Necesita un espacio amplio y cuidado regular.'),
(7, 'mediano', 'casa', 'joven', FALSE, TRUE, 'media', 'sociable', 'https://images.pexels.com/photos/4001296/pexels-photo-4001296.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Conejo', 'Un conejo joven ideal para espacios interiores.', 'Requiere una jaula cómoda y vegetales frescos.'),
(8, 'mediano', 'casa', 'adulto', TRUE, TRUE, 'baja', 'tranquilo', 'https://images.pexels.com/photos/3730206/pexels-photo-3730206.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Conejo', 'Un conejo adulto tranquilo.', 'Requiere un espacio tranquilo y cuidado regular.'),
(9, 'pequeño', 'apartamento', 'cria', TRUE, FALSE, 'media', 'jugueton', 'https://images.pexels.com/photos/2289387/pexels-photo-2289387.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Canario', 'Un canario joven que disfruta cantar.', 'Requiere una jaula limpia y alimentación adecuada.'),
(10, 'pequeño', 'apartamento', 'adulto', TRUE, FALSE, 'baja', 'tranquilo', 'https://images.pexels.com/photos/19599902/pexels-photo-19599902/free-photo-of-periquitos.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Canario', 'Un canario adulto ideal para un hogar tranquilo.', 'Requiere poca interacción y mantenimiento regular.'),
(11, 'pequeño', 'apartamento', 'joven', FALSE, TRUE, 'baja', 'independiente', 'https://images.pexels.com/photos/15316903/pexels-photo-15316903/free-photo-of-hamster-en-jarron.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Hamster', 'Un hámster joven que requiere poco espacio.', 'Requiere un hábitat pequeño y comida específica.'),
(12, 'pequeño', 'apartamento', 'adulto', FALSE, TRUE, 'baja', 'curioso', 'https://images.pexels.com/photos/3432929/pexels-photo-3432929.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Hamster', 'Un hámster adulto tranquilo y curioso.', 'Requiere limpieza frecuente de su jaula.'),
(13, 'pequeño', 'apartamento', 'joven', TRUE, FALSE, 'baja', 'tranquilo', 'https://images.pexels.com/photos/8434726/pexels-photo-8434726.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Pez', 'Un pez joven ideal para principiantes.', 'Requiere un acuario pequeño y cuidado básico.'),
(14, 'pequeño', 'apartamento', 'adulto', FALSE, FALSE, 'baja', 'independiente', 'https://images.pexels.com/photos/2053815/pexels-photo-2053815.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Pez', 'Un pez adulto de bajo mantenimiento.', 'Requiere un acuario limpio y agua tratada.'),
(15, 'pequeño', 'apartamento', 'adulto', FALSE, FALSE, 'baja', 'independiente', 'https://images.pexels.com/photos/3672148/pexels-photo-3672148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Araña', 'Una araña adulta para aficionados.', 'Requiere un terrario cerrado y cuidado mínimo.'),
(16, 'pequeño', 'apartamento', 'joven', FALSE, FALSE, 'media', 'curioso', 'https://images.pexels.com/photos/17817251/pexels-photo-17817251/free-photo-of-arbol-reptil-rama-fotografia-de-animales.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Serpiente', 'Una serpiente joven ideal para espacios pequeños.', 'Requiere un terrario adecuado y alimentación viva.'),
(17, 'mediano', 'apartamento', 'adulto', FALSE, FALSE, 'baja', 'tranquilo', 'https://images.pexels.com/photos/17817251/pexels-photo-17817251/free-photo-of-arbol-reptil-rama-fotografia-de-animales.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Serpiente', 'Una serpiente adulta tranquila.', 'Requiere control de temperatura y hábitat adecuado.'),
(18, 'mediano', 'apartamento', 'cria', TRUE, TRUE, 'media', 'jugueton', 'https://images.pexels.com/photos/2289387/pexels-photo-2289387.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Loro', 'Un loro cría muy sociable.', 'Requiere interacción constante y frutas frescas.'),
(19, 'mediano', 'apartamento', 'adulto', TRUE, FALSE, 'media', 'sociable', 'https://images.pexels.com/photos/29461116/pexels-photo-29461116.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Loro', 'Un loro adulto ideal para compañía.', 'Requiere un espacio amplio para volar.'),
(20, 'pequeño', 'apartamento', 'joven', TRUE, TRUE, 'media', 'curioso', 'https://images.pexels.com/photos/35669/hyla-meridionalis-the-frog-amphibians.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Rana', 'Una rana joven activa.', 'Requiere un acuaterrario y humedad constante.'),
(21, 'mediano', 'apartamento', 'cria', TRUE, TRUE, 'alta', 'curioso', 'https://images.pexels.com/photos/7179718/pexels-photo-7179718.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Huron', 'Un hurón cría ideal para familias activas.', 'Requiere supervisión constante y espacio para explorar.'),
(22, 'mediano', 'apartamento', 'adulto', TRUE, FALSE, 'media', 'independiente', 'https://images.pexels.com/photos/12131382/pexels-photo-12131382.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Huron', 'Un hurón adulto tranquilo.', 'Requiere juguetes y atención moderada.'),
(23, 'pequeño', 'apartamento', 'joven', FALSE, FALSE, 'baja', 'independiente', 'https://images.pexels.com/photos/18102591/pexels-photo-18102591/free-photo-of-agua-reptil-cascara-tortuga.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Tortuga', 'Una tortuga joven de bajo mantenimiento.', 'Requiere un acuaterrario adecuado y sol.'),
(24, 'mediano', 'apartamento', 'adulto', FALSE, TRUE, 'baja', 'tranquilo', 'https://images.pexels.com/photos/29566140/pexels-photo-29566140/free-photo-of-primer-plano-de-una-tortuga-de-agua-dulce-con-un-caparazon-con-un-patron-vibrante.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Tortuga', 'Una tortuga adulta tranquila.', 'Requiere control de temperatura y espacio amplio.'),
(25, 'pequeño', 'apartamento', 'joven', FALSE, TRUE, 'media', 'curioso', 'https://images.pexels.com/photos/19730407/pexels-photo-19730407/free-photo-of-camaleon-de-yemen.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Camaleon', 'Un camaleón joven activo.', 'Requiere un terrario con plantas y luz UV.'),
(26, 'pequeño', 'apartamento', 'joven', TRUE, TRUE, 'media', 'jugueton', 'https://images.pexels.com/photos/1161556/pexels-photo-1161556.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Ardilla', 'Una ardilla joven enérgica.', 'Requiere un espacio amplio y juguetes interactivos.');
